In [38]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [39]:
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import pymorphy2

In [40]:
#загрузка данных

df_p = pd.read_csv('datasets/positive.csv',sep=';', header=None)
df_n = pd.read_csv('datasets/negative.csv',sep=';', header=None)
df = pd.concat([df_p, df_n], ignore_index=True)
df

,0,1,2,3,4,5,6,7,8,9,10,11
0,408906692374446080,1386325927,pleease_shut_up,"@first_timee хоть я и школота, но поверь, у на...",1,0,0,0,7569,62,61,0
1,408906692693221377,1386325927,alinakirpicheva,"Да, все-таки он немного похож на него. Но мой ...",1,0,0,0,11825,59,31,2
2,408906695083954177,1386325927,EvgeshaRe,RT @KatiaCheh: Ну ты идиотка) я испугалась за ...,1,0,1,0,1273,26,27,0
3,408906695356973056,1386325927,ikonnikova_21,"RT @digger2912: ""Кто то в углу сидит и погибае...",1,0,1,0,1549,19,17,0
4,408906761416867842,1386325943,JumpyAlex,@irina_dyshkant Вот что значит страшилка :D\nН...,1,0,0,0,597,16,23,1
...,...,...,...,...,...,...,...,...,...,...,...,...
226829,425138243257253888,1390195830,Yanch_96,Но не каждый хочет что то исправлять:( http://...,-1,0,0,0,1138,32,46,0
226830,425138339503943682,1390195853,tkit_on,скучаю так :-( только @taaannyaaa вправляет мо...,-1,0,0,0,4822,38,32,0
226831,425138437684215808,1390195876,ckooker1,"Вот и в школу, в говно это идти уже надо(",-1,0,0,1,165,13,16,0
226832,425138490452344832,1390195889,LisaBeroud,"RT @_Them__: @LisaBeroud Тауриэль, не грусти :...",-1,0,1,0,2516,187,265,0
226833,425138595251625984,1390195914,sukapavlov,Такси везет меня на работу. Раздумываю приплат...,-1,0,0,0,7778,146,66,5

In [41]:
#пред подготовка таблицы

df.set_axis(['id', 'date', 'name', 'text', 'positive', 'rep', 'rtv', 'fav', 'total_count', 'fol', 'friends', 'list_count'], axis=1, inplace=True)
df['text'] = df.text.str.lower()
df.text = df.text.str.replace(r"[^А-Яа-я]"," ")
df.positive[df.positive==-1]=0
df

,id,date,name,text,positive,rep,rtv,fav,total_count,fol,friends,list_count
0,408906692374446080,1386325927,pleease_shut_up,хоть я и школота но поверь у на...,1,0,0,0,7569,62,61,0
1,408906692693221377,1386325927,alinakirpicheva,да все таки он немного похож на него но мой ...,1,0,0,0,11825,59,31,2
2,408906695083954177,1386325927,EvgeshaRe,ну ты идиотка я испугалась за ...,1,0,1,0,1273,26,27,0
3,408906695356973056,1386325927,ikonnikova_21,кто то в углу сидит и погибае...,1,0,1,0,1549,19,17,0
4,408906761416867842,1386325943,JumpyAlex,вот что значит страшилка но...,1,0,0,0,597,16,23,1
...,...,...,...,...,...,...,...,...,...,...,...,...
226829,425138243257253888,1390195830,Yanch_96,но не каждый хочет что то исправлять ...,0,0,0,0,1138,32,46,0
226830,425138339503943682,1390195853,tkit_on,скучаю так только вправляет мо...,0,0,0,0,4822,38,32,0
226831,425138437684215808,1390195876,ckooker1,вот и в школу в говно это идти уже надо,0,0,0,1,165,13,16,0
226832,425138490452344832,1390195889,LisaBeroud,тауриэль не грусти ...,0,0,1,0,2516,187,265,0
226833,425138595251625984,1390195914,sukapavlov,такси везет меня на работу раздумываю приплат...,0,0,0,0,7778,146,66,5

In [42]:
# обработка текста
df.text = list(map(word_tokenize, df.text))
df.text.loc[0:5]

0    [хоть, я, и, школота, но, поверь, у, нас, то, ...
1    [да, все, таки, он, немного, похож, на, него, ...
2           [ну, ты, идиотка, я, испугалась, за, тебя]
3    [кто, то, в, углу, сидит, и, погибает, от, гол...
4    [вот, что, значит, страшилка, но, блин, посмот...
5    [ну, любишь, или, нет, я, не, знаю, кто, ты, бля]
Name: text, dtype: object

In [43]:
def delete_stopword(words):
    russian_stopwords = stopwords.words("russian")
    new_s = [word for word in words if word not in russian_stopwords]
    return new_s
df.text = list(map(delete_stopword, df.text))
df.text.loc[0:5]

0    [школота, поверь, самое, общество, профилирующ...
1               [таки, немного, похож, мальчик, равно]
2                                [идиотка, испугалась]
3    [углу, сидит, погибает, голода, ещ, порции, вз...
4    [значит, страшилка, блин, посмотрев, части, со...
5                                  [любишь, знаю, бля]
Name: text, dtype: object

In [44]:
def lemmatization(words):
    global morph
    new_s = [morph.parse(word)[0].normal_form for word in words]
    return new_s
morph = pymorphy2.MorphAnalyzer()
df.text = list(map(lemmatization, df.text))
df.text.loc[0:5]

0    [школотый, поверь, самый, общество, профилиров...
1             [таки, немного, похожий, мальчик, равно]
2                                [идиотка, испугаться]
3    [угол, сидеть, погибать, голод, ещ, порция, вз...
4    [значит, страшилка, блин, посмотреть, часть, с...
5                                 [любить, знать, бля]
Name: text, dtype: object

In [100]:
df = df.drop(df[df.text == ''].index, axis = 0)
df

,id,date,name,text,positive,rep,rtv,fav,total_count,fol,friends,list_count
0,408906692374446080,1386325927,pleease_shut_up,"[школотый, поверь, самый, общество, профилиров...",1,0,0,0,7569,62,61,0
1,408906692693221377,1386325927,alinakirpicheva,"[таки, немного, похожий, мальчик, равно]",1,0,0,0,11825,59,31,2
2,408906695083954177,1386325927,EvgeshaRe,"[идиотка, испугаться]",1,0,1,0,1273,26,27,0
3,408906695356973056,1386325927,ikonnikova_21,"[угол, сидеть, погибать, голод, ещ, порция, вз...",1,0,1,0,1549,19,17,0
4,408906761416867842,1386325943,JumpyAlex,"[значит, страшилка, блин, посмотреть, часть, с...",1,0,0,0,597,16,23,1
...,...,...,...,...,...,...,...,...,...,...,...,...
226829,425138243257253888,1390195830,Yanch_96,"[каждый, хотеть, исправлять]",0,0,0,0,1138,32,46,0
226830,425138339503943682,1390195853,tkit_on,"[скучать, вправлять, мозг, равно, скучать]",0,0,0,0,4822,38,32,0
226831,425138437684215808,1390195876,ckooker1,"[школа, говно, это, идти]",0,0,0,1,165,13,16,0
226832,425138490452344832,1390195889,LisaBeroud,"[тауриэль, грусть, обнять]",0,0,1,0,2516,187,265,0
226833,425138595251625984,1390195914,sukapavlov,"[такси, везти, работа, раздумывать, приплатить...",0,0,0,0,7778,146,66,5

In [61]:
# df.to_csv("clean_df.csv" ,index=False)

In [89]:
# df_cl = pd.read_csv('clean_df.csv')
# df_cl['text'] = df_cl['text'].apply(lambda x: x[2:-2].split("', '"))
# df_cl